# MODO SEGURO: TLS 1.2+, usuário/senha por nó e ACL por tópico.
persistence false
listener 8883
cafile   /mosquitto/secure/certs/ca.crt
certfile /mosquitto/secure/certs/server.crt
keyfile  /mosquitto/secure/certs/server.key
tls_version tlsv1.2
allow_anonymous false
password_file /mosquitto/secure/passwd
acl_file /mosquitto/secure/acl
message_size_limit 1024
max_connections 20
